name: Build LineageOS for dizi

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout empty repo
        uses: actions/checkout@v3

      - name: Setup Docker Build Folders
        run: |
          mkdir -p zips logs ccache

      - name: Run LineageOS MicroG Docker Build
        run: |
          docker run \
            -e "BRANCH_NAME=lineage-20.0" \
            -e "DEVICE_LIST=dizi" \
            -e "INCLUDE_PROPRIETARY=true" \
            -e "SIGN_BUILDS=true" \
            -e "WITH_GAPPS=false" \
            -e "WITH_MICROG=true" \
            -e "DEBUG=true" \
            -v ${{ github.workspace }}:/srv/src \
            -v ${{ github.workspace }}/zips:/srv/zips \
            -v ${{ github.workspace }}/logs:/srv/logs \
            -v ${{ github.workspace }}/ccache:/srv/ccache \
            lineageos4microg/docker-lineage-cicd

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lineageos-dizi
          path: zips/
